/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:     sensirion-driver-generator 1.7.0
 * Product:       sen63c
 * Model-Version: 1.3.1
 */
/*
 * Copyright (c) 2026, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
#include <Arduino.h>
#include <SensirionI2cSen63c.h>
#include <Wire.h>

// macro definitions
// make sure that we use the proper definition of NO_ERROR
#ifdef NO_ERROR
#undef NO_ERROR
#endif
#define NO_ERROR 0

SensirionI2cSen63c sensor;

static char errorMessage[64];
static int16_t error;

void setup() {

    Serial.begin(115200);
    while (!Serial) {
        delay(100);
    }
    Wire.begin();
    sensor.begin(Wire, SEN63C_I2C_ADDR_6B);

    error = sensor.deviceReset();
    if (error != NO_ERROR) {
        Serial.print("Error trying to execute deviceReset(): ");
        errorToString(error, errorMessage, sizeof errorMessage);
        Serial.println(errorMessage);
        return;
    }
    delay(1200);
    int8_t serialNumber[32] = {0};

    error = sensor.getSerialNumber(serialNumber, 32);
    if (error != NO_ERROR) {
        Serial.print("Error trying to execute getSerialNumber(): ");
        errorToString(error, errorMessage, sizeof errorMessage);
        Serial.println(errorMessage);
        return;
    }
    Serial.print("serialNumber: ");
    Serial.print((const char*)serialNumber);
    Serial.println();

    Serial.print("Fan Cleaning Start");
    Serial.println();
    error = sensor.startFanCleaning();
    if (error != NO_ERROR) {
        Serial.print("Error trying to execute startFanCleaning(): ");
        errorToString(error, errorMessage, sizeof errorMessage);
        Serial.println(errorMessage);
        return;
    }
    delay(10000);
    Serial.print("Fan Cleaning Finished");
    Serial.println();

    error = sensor.startContinuousMeasurement();
    if (error != NO_ERROR) {
        Serial.print("Error trying to execute startContinuousMeasurement(): ");
        errorToString(error, errorMessage, sizeof errorMessage);
        Serial.println(errorMessage);
        return;
    }
    Serial.print("Initializing CO2 Sensor");
    Serial.println();
    delay(30000);
    Serial.print("Initialization Complete");
    Serial.println();
}

void loop() {

    float particulateSizeLessThan1um = 0.0;     //unit == ug/m^3
    float particulateSizeLessThan2P5um = 0.0;   
    float particulateSizeLessThan4um = 0.0;
    float particulateSizeLessThan10um = 0.0;
    float humidity = 0.0;                       //percent
    float temperature = 0.0;                    //degC
    int16_t co2 = 0;                            //ppm
    bool dataReady = 0x0;
    uint8_t padding = 0x0;
    // int PM1 = 0;        // PM1 AQI. 0-5 scale with 0 is good, 5 is hazardous

    delay(1000);
    sensor.getDataReady(padding, dataReady);
    if (dataReady == 1)
    {
        error = sensor.readMeasuredValues(
        particulateSizeLessThan1um, particulateSizeLessThan2P5um, particulateSizeLessThan4um,
        particulateSizeLessThan10um, humidity, temperature, co2);
        if (error != NO_ERROR) {
            Serial.print("Error trying to execute readMeasuredValues(): ");
            errorToString(error, errorMessage, sizeof errorMessage);
            Serial.println(errorMessage);
            return;
        }

        // switch (PM1)
        // {
        // case 0:
        //     Serial.print("PM1 Good");
        //     Serial.print("\t");
        //     break;
        // case 1:
        //     Serial.print("PM1 Moderate");
        //     Serial.print("\t");
        // case 2:
        //     Serial.print("PM1 Unhealthy for Sensitive Groups");
        //     Serial.print("\t");
        //     break;
        // case 3:
        //     Serial.print("PM1 Unhealthy");
        //     Serial.print("\t");
        //     break;
        // case 4:
        //     Serial.print("PM1 Very Unhealthy");
        //     Serial.print("\t");
        //     break;
        // case 5:
        //     Serial.print("PM1 Hazardous");
        //     Serial.print("\t");
        //     break;
        // default:
        //     Serial.print("error i guess");
        //     Serial.print("\t");
        //     break;
        // }

            Serial.print("PM1: ");
            Serial.print(particulateSizeLessThan1um);
            Serial.print("\t");

            Serial.print("PM2.5: ");
            Serial.print(particulateSizeLessThan2P5um);
            Serial.print("\t");

            Serial.print("PM4: ");
            Serial.print(particulateSizeLessThan4um);
            Serial.print("\t");

            Serial.print("PM10: ");
            Serial.print(particulateSizeLessThan10um);
            Serial.print("\t");

            Serial.print("humidity: ");
            Serial.print(humidity);
            Serial.print("\t");

            Serial.print("temp: ");
            Serial.print(temperature);
            Serial.print("\t");
            
            Serial.print("co2: ");
            Serial.print(co2);
            Serial.println();
    }
    else{
        return;
    }
    
}
